services:

  superset:
    build:
      context: .
      dockerfile: docker/superset/Dockerfile
    image: superset-custom:1.0
    container_name: superset
    restart: unless-stopped

    ports:
      - "8088:8088"

    environment:
      SUPERSET_SECRET_KEY: "superset_secret_key_devops_platform"

    volumes:
      - ./dashboards/superset/data:/app/superset_home
      - ./dashboards/superset/config/superset_config.py:/app/pythonpath/superset_config.py

    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
