groups:
  - name: platform-alerts
    rules:

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service DOWN"
          description: "Le service {{ $labels.instance }} est indisponible."
